### ISSUE TITLE
Inconsistent Navigation

### ISSUE THREAD

**Issue by abkaaar** [abkaaar/allospace#5]
Hub Mangers cannot Navigate to dashboard from any other page except from home page. therefore we need to address it by making navigations from everyother page to homepage else it is going to show "404 - go back to homepage"

example: you cant navigate to "https://allospace.co/coworking-desks/dashboard" except "https://allospace.co/dashboard"
which is not consistent.

**Comment by abkaaar** [comment]
I Hope you noticed it too.

**Comment by abkaaar** [comment]
this has been resolved.

**Comment by abkaaar** [comment]
https://github.com/abkaaar/allospace/issues/5#issuecomment-2558257710

**Comment by looju** [comment]
ok great. Just was about to fix it
